project:
  type: book

book:
  title: "fleetR: Airline Fleet Explorer Documentation"
  author: "Martin Stavro"
  date: "9/30/2025"
  chapters:
    - index.qmd
    - intro.qmd
    - data_sources.qmd
    - get_data.qmd
    - fleet_data.qmd
    - map_tables.qmd
    - deployment.qmd
    - conclusion.qmd

format:
  html:
    theme:
      - cosmo
      - brand
      - fleetR.scss



